version: '3'

services:
  muuvis.catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "1234:80"
  db:
    environment:
      SA_PASSWORD: "Test1234"
    ports:
      - "1433:1433"
  bus:
    ports:
      - "8080:15672"
networks:
  default:
    external:
      name: nat
