version: '3.4'

services:
  catalog:
    image: ${SITE}.azurecr.io/catalog:${TAG}
    build:
      context: .
      dockerfile: Catalog/Catalog.WebApi/Dockerfile
    environment:
      basePath: /catalog
      Cqrs__AzureServiceBusConnectionString: "${BUS}"
      Cqrs__SqlServerConnectionString: "${SQLCATALOG}"
      ConnectionStrings__SqlServer: "${SQLCATALOG}"
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/ContainerLogs:/var/log/containers

  taste:
    image: ${SITE}.azurecr.io/taste:${TAG}
    build:
      context: .
      dockerfile: Taste/Taste.WebApi/Dockerfile
    environment:
      basePath: /taste
      Cqrs__AzureServiceBusConnectionString: "${BUS}"
      Cqrs__SqlServerConnectionString: "${SQLTASTE}"
      ConnectionStrings__SqlServer: "${SQLTASTE}"
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/ContainerLogs:/var/log/containers

  frontdoor:
    image: ${SITE}.azurecr.io/frontdoor:${TAG}
    build:
      context: .
      dockerfile: FrontDoor/Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - taste
      - catalog